// seedCourses.js – Native MongoDB seeding

require("dotenv").config();
const { MongoClient } = require("mongodb");
console.log("MONGO URI BEING USED:", process.env.MONGO_URI);


const uri = process.env.MONGO_URI;
const client = new MongoClient(uri);

const courses = [
  {
    id: 1,
    title: "Web Development Bootcamp",
    category: "Development",
    instructor: "John Doe",
    rating: 4.8,
    reviews: 10200,
    price: 49.99,
    available: 7,
    location: "Apo District, Abuja",
    image: "https://images.unsplash.com/photo-1505685296765-3a2736de412f?w=800",
    details: ["HTML, CSS, JS", "Real projects", "Deploy professionally"],
  },
  {
    id: 2,
    title: "React Frontend Development",
    category: "Development",
    instructor: "Chris Walker",
    rating: 4.7,
    reviews: 7800,
    price: 44.99,
    available: 5,
    location: "Garki, Abuja",
    image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=800",
    details: ["React Hooks", "Components", "Deploy to Netlify"],
  },
  {
    id: 3,
    title: "Flutter Mobile Development",
    category: "Mobile Development",
    instructor: "Sarah Johnson",
    rating: 4.6,
    reviews: 6300,
    price: 39.99,
    available: 9,
    location: "Maitama, Abuja",
    image: "https://images.unsplash.com/photo-1555066931-bf19f8fd1085?w=800",
    details: ["Dart Basics", "UI Widgets", "Publish Apps"],
  },
  {
    id: 4,
    title: "Node.js Backend Mastery",
    category: "Backend Development",
    instructor: "Michael Smith",
    rating: 4.7,
    reviews: 5400,
    price: 42.99,
    available: 6,
    location: "Wuse Zone 5, Abuja",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    details: ["Express.js", "MongoDB", "APIs"],
  },
  {
    id: 5,
    title: "Full-Stack Web Development Roadmap",
    category: "Development",
    instructor: "David Lee",
    rating: 4.9,
    reviews: 15000,
    price: 59.99,
    available: 10,
    location: "Gwarinpa, Abuja",
    image: "https://images.unsplash.com/photo-1556155092-490a1ba16284?w=800",
    details: ["Frontend + Backend", "Real-world systems", "Deploy full apps"],
  },
  {
    id: 6,
    title: "UI/UX Design Masterclass",
    category: "Design",
    instructor: "Emily Brown",
    rating: 4.8,
    reviews: 8500,
    price: 39.99,
    available: 8,
    location: "Lokogoma, Abuja",
    image: "https://images.unsplash.com/photo-1522199710521-72d69614c702?w=800",
    details: ["Figma", "Prototyping", "Design Systems"],
  },
  {
    id: 7,
    title: "Graphic Design Essentials",
    category: "Design",
    instructor: "Daniel Martinez",
    rating: 4.5,
    reviews: 4200,
    price: 29.99,
    available: 12,
    location: "Kuje, Abuja",
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?w=800",
    details: ["Adobe Illustrator", "Logo Design", "Branding"],
  },
  {
    id: 8,
    title: "Photoshop for Beginners",
    category: "Design",
    instructor: "Emma Wilson",
    rating: 4.4,
    reviews: 3000,
    price: 24.99,
    available: 15,
    location: "Abuja Central",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    details: ["Photo Editing", "Layering", "Color Adjustment"],
  },
  {
    id: 9,
    title: "Python Programming",
    category: "Development",
    instructor: "Andrew Davis",
    rating: 4.9,
    reviews: 9200,
    price: 54.99,
    available: 11,
    location: "Life Camp, Abuja",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800",
    details: ["Python Basics", "Automation", "Mini Projects"],
  },
  {
    id: 10,
    title: "Java Programming Masterclass",
    category: "Development",
    instructor: "Sophia Thompson",
    rating: 4.7,
    reviews: 7500,
    price: 49.99,
    available: 7,
    location: "Utako, Abuja",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800",
    details: ["OOP", "Data Structures", "Java Apps"],
  },

  /* ---------- Continue remaining 10 courses ---------- */

  {
    id: 11,
    title: "C++ for Beginners",
    category: "Development",
    instructor: "Kevin Jordan",
    rating: 4.3,
    reviews: 3800,
    price: 34.99,
    available: 12,
    location: "Lugbe, Abuja",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800",
    details: ["C++ Basics", "Pointers", "Algorithms"],
  },
  {
    id: 12,
    title: "JavaScript Mastery",
    category: "Development",
    instructor: "Olivia Harris",
    rating: 4.8,
    reviews: 11000,
    price: 44.99,
    available: 9,
    location: "Wuse II, Abuja",
    image: "https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800",
    details: ["ES6", "Asynchronous JS", "DOM Projects"],
  },
  {
    id: 13,
    title: "SQL Database Essentials",
    category: "Development",
    instructor: "William Moore",
    rating: 4.6,
    reviews: 6500,
    price: 29.99,
    available: 14,
    location: "Abuja Central",
    image: "https://images.unsplash.com/photo-1518972559570-7cc1309f3229?w=800",
    details: ["SQL Queries", "Joins", "Database Design"],
  },
  {
    id: 14,
    title: "Digital Marketing Bootcamp",
    category: "Marketing",
    instructor: "Grace Miller",
    rating: 4.7,
    reviews: 7700,
    price: 39.99,
    available: 10,
    location: "Garki, Abuja",
    image: "https://images.unsplash.com/photo-1508830524289-0adcbe822b40?w=800",
    details: ["SEO", "Email Marketing", "Analytics"],
  },
  {
    id: 15,
    title: "Social Media Strategy",
    category: "Marketing",
    instructor: "Ryan Anderson",
    rating: 4.5,
    reviews: 4300,
    price: 24.99,
    available: 13,
    location: "Asokoro, Abuja",
    image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800",
    details: ["Instagram", "TikTok", "Campaign Growth"],
  },
  {
    id: 16,
    title: "Google Ads Certification",
    category: "Marketing",
    instructor: "Hannah Lewis",
    rating: 4.6,
    reviews: 5400,
    price: 29.99,
    available: 9,
    location: "Jabi, Abuja",
    image: "https://images.unsplash.com/photo-1532614338840-ab30cf10ed36?w=800",
    details: ["Google Ads", "Analytics", "Keyword Targeting"],
  },
  {
    id: 17,
    title: "Content Writing Mastery",
    category: "Marketing",
    instructor: "Jacob Evans",
    rating: 4.4,
    reviews: 4000,
    price: 19.99,
    available: 16,
    location: "Area 1, Abuja",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800",
    details: ["Content Strategy", "Copywriting", "Brand Voice"],
  },
  {
    id: 18,
    title: "Project Management Essentials",
    category: "Business",
    instructor: "Sophia Carter",
    rating: 4.6,
    reviews: 5500,
    price: 39.99,
    available: 12,
    location: "Wuye, Abuja",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800",
    details: ["Agile", "Scrum", "Product Delivery"],
  },
  {
    id: 19,
    title: "Entrepreneurship Foundations",
    category: "Business",
    instructor: "Lucas White",
    rating: 4.5,
    reviews: 3900,
    price: 34.99,
    available: 15,
    location: "Jikwoyi, Abuja",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800",
    details: ["Startups", "Business Models", "Market Research"],
  },
  {
    id: 20,
    title: "Financial Literacy for Beginners",
    category: "Business",
    instructor: "Ella Scott",
    rating: 4.3,
    reviews: 3100,
    price: 22.99,
    available: 20,
    location: "Gwarinpa, Abuja",
    image: "https://images.unsplash.com/photo-1554224154-22dec7ec8818?w=800",
    details: ["Saving", "Budgeting", "Investing"],
  },
];

// --- Database Connection ---
async function seed() {
  try {
    await client.connect();
    const db = client.db("smartclass"); // change if needed
    const lessonsCol = db.collection("lessons");

    console.log("🗑️ Clearing old lessons...");
    await lessonsCol.deleteMany({});

    console.log("🌱 Inserting new lessons...");
    await lessonsCol.insertMany(courses);

    console.log("✅ Seeding complete!");
  } catch (err) {
    console.error("❌ Seeding error:", err);
  } finally {
    await client.close();
  }
}

seed();
